import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';
import '../services/database_service.dart';
import '../models/story.dart';

class CreateStoryScreen extends StatefulWidget {
  const CreateStoryScreen({super.key});

  @override
  State<CreateStoryScreen> createState() => _CreateStoryScreenState();
}

class _CreateStoryScreenState extends State<CreateStoryScreen> {
  File? _imageFile;
  final TextEditingController _captionController = TextEditingController();
  bool _isLoading = false;

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);

    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  Future<void> _uploadStory() async {
    if (_imageFile == null) return;

    setState(() {
      _isLoading = true;
    });

    try {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final user = authProvider.user!;
      
      final imageUrl = await DatabaseService().uploadFile(
        'stories_${user.uid}', 
        _imageFile!, 
        'story_${DateTime.now().millisecondsSinceEpoch}.jpg'
      );

      final story = Story(
        id: '', // Generated by Firestore
        uploaderId: user.uid,
        mediaUrl: imageUrl,
        mediaType: 'image',
        caption: _captionController.text,
        timestamp: DateTime.now(),
        viewers: [],
      );

      await DatabaseService().uploadStory(story);

      if (mounted) {
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error uploading story: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Story'),
        actions: [
          if (_imageFile != null && !_isLoading)
            IconButton(
              icon: const Icon(Icons.check),
              onPressed: _uploadStory,
            ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              child: Column(
                children: [
                  if (_imageFile != null)
                    Image.file(
                      _imageFile!,
                      height: 400,
                      width: double.infinity,
                      fit: BoxFit.cover,
                    )
                  else
                    GestureDetector(
                      onTap: _pickImage,
                      child: Container(
                        height: 400,
                        color: Colors.grey[300],
                        child: const Center(
                          child: Icon(Icons.add_a_photo, size: 50),
                        ),
                      ),
                    ),
                  Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: TextField(
                      controller: _captionController,
                      decoration: const InputDecoration(
                        hintText: 'Add a caption...',
                        border: InputBorder.none,
                      ),
                    ),
                  ),
                ],
              ),
            ),
    );
  }
}
